<#include "header.ftlh"/>

<#macro content>
    <div class="container">
        <div class="information"></div>
        LifeCare is an encyclopedia of knowledge about survival in difficult life situations. Here you can find articles on how to behave in the wild, what to do when faced with a wild animal, how to provide first aid for various types of injuries and many other useful things.
    </div>
    </div>
</#macro>

<#macro  title>
    LifeCare
</#macro>

<@main/>